---
# Deploy the latest version of the application to the production environment

- name: deploy the latest application version to production
  hosts: project--bas-style-kit:&env--prod
  remote_user: "{{ privileged_remote_user }}"
  become: yes
  tasks:
    - name: ensure directory for application exists
      file:
        path="{{ app_project_directory }}"
       state=directory
    - name: deploy latest project using rsync
      synchronize:
             src=../
            dest="{{ app_project_directory }}"
        checksum=yes
           times=no
